# -*- coding: utf-8 -*-
"""Mohit kumar,BCA2nd,A,P-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PstKTWikVk3tWVOjAryWDTK7-7TqVw_C

Project 2 (Indian Diabetes Data Analysis)
Mohit Kumar
BCA 2nd sem, A
Year-(2020-2023)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/drive/MyDrive/pima-indians-diabetes.csv")

data.head(5)

data.shape

data.isnull().sum()

data.head(4)

data.rename(columns = {'DiabetesPedigreeFunction':'D_P_F'}, inplace = True)
data.head(4)

data.describe()

sns.boxplot(data.D_P_F)

data.corr()

sns.heatmap(data.corr(),annot=True)

plt.scatter(data.Age,data.Glucose,color="red",marker="+")

from sklearn import linear_model
model=linear_model.LinearRegression()
model.fit(data[["Glucose"]],data.Age)
model

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data[['Age']],data[['Glucose']],train_size=0.7)

X_test
X_train
y_train
y_test
y_predicted=model.predict(X_test)

X_test.head(2)

X_train.head(2)

y_train.head(2)

y_test.head(2)

model.predict([[0.356]])

plt.scatter(data.Glucose,data.Age,color="red",marker="+")
plt.plot(data.Glucose,model.predict(data[["Age"]]))